### PR TITLE
Bicycle model translation from front axle to tow hitch 

### LINKED ISSUE #15: [Model design] Bicycle model translation from front axle to tow hitch
Create a translation matrix from front axle to rear bumper + hitch.
Please follow image attached as reference.
image

On next results, please show x,y plot.
Take a look into [here](https://my.eng.utah.edu/~stulp/) to plot vehicle + trailer in order to get more understandable results

### PR DESCRIPTION
**Pull request by raul-rd**
Bicycle model translation from front axle to tow hitch. 
Please, when you finish simulating the model, run the PlotPositionReferenceAxisAndHitch.m file to display the results.

### CODE REVIEW

**Comment by jcontrolresearch** [comment]
It should be great if provide XY plot as following

image

including:

start point
direction vehicle
and some diagram to show vehicle and hitch reference points

What{s your opinion @SaraML , @lfc-256 , @HugoLeyvaOax , @lfc-256 ?

**Comment by raul-rd** [comment]
Update the model according to the comments.

#23d6394fbc3fd1b03a114f33dc4905aa984058ba

**Comment by raul-rd** [comment]
23d6394fbc3fd1b03a114f33dc4905aa984058ba

**Comment by raul-rd** [comment]
Update the model according to the comments.

This is the commit: 23d6394fbc3fd1b03a114f33dc4905aa984058ba

**Review by jcontrolresearch — APPROVED** [review]
Great job!

**Review by SaraML — APPROVED** [review]

**Review by lfc-256 — APPROVED** [review]

**Review by HugoLeyvaOax — APPROVED** [review]
very well!

**Pull request merged**
