### PR TITLE
Bicycle model vehicle

### PR DESCRIPTION
**Pull request by SaraML**
Black box model of bicycle
Inputs:
- [v] : Speed
- [Df] : Steering angle
You can chose between two steering angle, the first one for go straight, turn and then straight again. The second one is a circular trajectory.

Outputs:
- [x1,y1] : X and Y position 
- [theta] : Heading of the bicycle

### CODE REVIEW

**Review by jcontrolresearch — CHANGES_REQUESTED** [review]
Please provide x,y graph.
Use code provided in:

[Bicycle_model_translation_from_front_axle_to_tow_hitch](https://github.com/lfc-256/ControlBDA/tree/Bicycle_model_translation_from_front_axle_to_tow_hitch)

provided by @raul-rd

**Comment by SaraML** [comment]
In the commit 82a52382fd30426830e5a911bd7f38b4b93a311c you can find the changes requested

**Review by jcontrolresearch — APPROVED** [review]

**Comment by jcontrolresearch** [comment]
@HugoLeyvaOax , @raul-rd , @lfc-256 could you please provide a comment/ change request / approval to this issue in order to close it ASAP?

**Review by raul-rd — APPROVED** [review]

**Review by HugoLeyvaOax — APPROVED** [review]
Very well!

**Pull request merged**
