### PR TITLE
TASK: Bicycle model vehicle+trailer

### PR DESCRIPTION
**Pull request by jcontrolresearch**
Simulink model vehicle + trailer. Taken from [here](External/Bibliography/lundquist2006.pdf).
This model follow geometric approach, now is working for constant steering wheel input.

What do you think to use this model to dev control?
It's accurate enough?

@lfc-256 , @SaraML , @raul-rd  could you improve the way to display (x,y) position + angle?

from [here](External/Bibliography/lundquist2006.pdf), model is referenced to P_1 reference point. 

image

From equations 
image
Could you please calculate x_2, y_2 position of trailer in order to plot as @raul-rd vehicle + trailer plot?

### CODE REVIEW

**Comment by lfc-256** [comment]
@JControlReserch Can you try with the model include in Matlab? and convert the file e4cc53a8a4d5b038d887240703905ad1b252f1e9 to compatibility version for Matlab R2015a? Thanks!!

**Comment by jcontrolresearch** [comment]
@lfc-256 pleas find model in *.mdl file. It should be compatible with previous version of MATLAB (earlier 2015)

Commit: 1137eeaf753feef1374ebe90c96712f8a4bcd78e

**Comment by jcontrolresearch** [comment]
@raul-rd , @SaraML , @lfc-256  please find updated models on last commit :)

**Comment by jcontrolresearch** [comment]
We are continuing on @raul-rd code

**Pull request merged**
